name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t bitleaf/php-app .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push bitleaf/php-app:latest
  
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws-personal-key.pem ec2-user@${{ secrets.SERVER_URL }} << 'EOF'
          docker pull bitleaf/php-app:latest
          docker stop php-app || true
          docker rm php-app || true
          docker run -d --name php-app -p 80:80 bitleaf/php-app:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_URL: ${{ secrets.SERVER_URL }}

  test:
    name: Test Application
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y curl jq chromium-browser

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium
        run: pip install selenium

      - name: Download and set up Chromedriver
        run: |
          curl -LO https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests
        run: python test_script.py ${{ secrets.SERVER_URL }}
