name: Test Application

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y curl jq chromium-browser

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium
        run: pip install selenium

      - name: Download and set up Chromedriver
        run: |
          curl -LO https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests
        run: python testing.py ${{ secrets.SERVER_URL }}
